Add AUCC verification
Desbordante/desbordante-core pull request #368
Opened 2024-03-07 14:10 UTC by Popov-Dmitriy-Ivanovich

2024-03-21 18:06 UTC, Mstrutov requested changes

2024-03-21 18:06 UTC, Mstrutov commented on src/core/algorithms/ucc/ucc_verifier/ucc_stats_calculator.h
> +}  // namespace algos
ругается на отсутствие newline (в examples/verifying_aucc.py тоже)

2024-03-21 18:06 UTC, Mstrutov commented on cli/cli.py
> +by Y.Huntala et al. For more information on AUCC, refer to "Efficient Discovery
полагаю, `For more information on AUCC` -> `For more information on UCC`

2024-03-21 18:06 UTC, Mstrutov commented on examples/verifying_aucc.py
> +        print('UCC holds, showing stats for AUCC is usless')
опечатка `usless`

2024-04-06 13:27 UTC, Popov-Dmitriy-Ivanovich commented on src/tests/test_ucc_verifier.cpp
> +    double expected_error_ = 0.0;
Странное сообщение, бот предлагает заменить строку на точно такую же строку, при этом 52 и 29 строки в коде именно такие, как в его предложении, откуда он взял "минусовые" строки не понятно

2024-04-13 10:48 UTC, Mstrutov commented on src/tests/test_ucc_verifier.cpp
> +    double expected_error_ = 0.0;
ок, видимо багануло

2024-04-13 10:49 UTC, Mstrutov approved these changes

2024-04-13 10:50 UTC, merged