Generalize TANE-based algorithms,
Desbordante/desbordante-core pull request #378
Opened 2024-03-22 22:31 UTC by iliya-b

2024-04-19 08:51 UTC, iliya-b commented
@vs9h I've fixed the architectural issues with Tane and PFDTane algorithms as you suggested in [PR #300 ](https://github.com/Desbordante/desbordante-core/pull/300#issuecomment-1846210843)

2024-08-17 12:58 UTC, vs9h requested changes
Firstly, I would like to suggest getting rid of the second pull request and doing everything within this one pull request. That is, adding the refactoring from the second pull request to this pull request.

I also have some suggestions regarding a small change in the code structure, I suggest splitting the files as follows:
```
├── tane
│ ├── enums.h
│ ├── model
│ │ ├── lattice_level.cpp
│ │ ├── lattice_level.h
│ │ ├── lattice_vertex.cpp
│ │ └── lattice_vertex.h
│ ├── pfdtane.cpp
│ ├── pfdtane.h
│ ├── tane_common.cpp
│ ├── tane_common.h
│ ├── tane.cpp
│ └── tane.h
```

That is, we will separate the base class into a separate file and the implementation of the algorithms into a separate file.

2024-08-17 12:58 UTC, vs9h commented on src/core/algorithms/fd/tane/tane.h
>      void ResetStateFd() final;
let's write definition right here
```suggestion
    void ResetStateFd() final {}
```

2024-09-10 15:02 UTC, iliya-b commented
@vs9h I've fixed the issues with this PR. You mentioned another PR #396 , but that PR is still a draft and it rather introduces a few performance enhances into the algorithm and does not affect the architecture. The current PR blocks some other PRs, that's why I've kept only changes that are related to this PR (refactoring) for this moment. What do you think?

2024-09-15 10:16 UTC, vs9h requested changes
Okay, let's deal with this pull request first. It's probably better this way.

2024-09-15 10:16 UTC, vs9h commented on src/core/algorithms/fd/tane/pfdtane.h
> +class PFDTane : public tane::TaneCommon {
Can you add some description for the algorithm class? (it can be a small comment like for `Pyro` or a full one like for `HyFD`)

2024-09-15 10:16 UTC, vs9h commented on src/core/algorithms/fd/tane/pfdtane.cpp
> +#include <easylogging++.h>
unused

2024-09-15 10:16 UTC, vs9h commented on src/core/algorithms/fd/tane/pfdtane.cpp
> +using boost::dynamic_bitset;
unused

2024-09-15 10:16 UTC, vs9h commented on src/core/algorithms/fd/tane/tane_common.cpp
>  using Cluster = model::PositionListIndex::Cluster;
unused

2024-09-15 20:06 UTC, vs9h commented
Also, split commits into at least two (tests in a separate commit)

2024-09-16 21:05 UTC, iliya-b commented
@vs9h I've fixed these issues.

2024-09-20 21:48 UTC, vs9h reviewed
Okay, I think we've come to something pretty good, I just left one small comment about public method in `TaneCommon` (after fixing that I will immediately click approve). 

But I have some more interesting ideas (probably for the future) to improve the current solution a bit from an architectural point of view.

Still, I really don't like the idea of ​​adding such public methods to the `PFDTane` class. I think it would be much better to try to somehow avoid using them.

I don't like that we put some information about the implementation in the public part, although we could avoid it somehow. All we need is to be able to get error information for a particular dependency.

For example, we could try to add a method that would allow the user to get information about the error of a particular functional dependency. (user can pass `RawFD` and get the information about the error of this dependency: `static double PFDTane::CalculatePFDError(const RawFD& rawfd)`).

Or another interesting idea is to add a separate class for pfd (which will probably inherit from fd) and in this class we will also store information about the error level of the dependency (there will probably be a lot of challenges when trying to add this, how well it fits into the existing code).

In this case, of course, we will have to add a new `PFDAlgorithm` class. This will add several other problems that will need to be solved. For example, we will need to do something with the `PliBasedFDAlgorithm` class, since it inherits from `FDAlgorithm`, and so on.

And we will also have to change the inheritance hierarchy, we will have to try to take out the common part with the implementation of algorithms. We can certainly avoid inheritance from the base class (`TaneCommon`) if we take a close look at the existing implementations of common parts for some algorithms (for example, for `Pyro` and `HyFD`).

At the same time, we will most likely be able to completely get rid of the use of virtual methods.

All the thoughts that I wrote above are just reflections on possible improvements and, in my opinion, they will help us get a better solution from an architectural point of view. If we can also give the user precise information about the error, then this will be very convenient for the user. But at the same time, the current solution is acceptable.

2024-09-20 21:48 UTC, vs9h commented on src/core/algorithms/fd/tane/tane_common.h
> +                                    ColumnLayoutRelationData const* relation_data);
Wow, I've never noticed that there (in the original `class Tane`) are such strange architectural decisions in the master branch now (namely, strange public fields and methods).

It seems to me that this public method should also be protected or even private if it is not planned to be used directly in the inherited classes.

2024-09-23 11:04 UTC, vs9h approved these changes

2024-09-23 19:44 UTC, merged