Implement mining of Afds based on pdep \tau mu+ and \rho measures
Desbordante/desbordante-core pull request #458
Opened 2024-09-10 21:32 UTC by egshnov

Pull request to ref in paper, actual pull request awaits #378

2024-10-16 14:05 UTC, Sched71 requested changes

2024-10-16 14:05 UTC, Sched71 commented on src/core/algorithms/fd/tane/tane.cpp
> +    x_frequencies[0] = 1;
Shouldn't here be: `std::unordered_map<unsigned, std::size_t> x_frequencies`?

2024-10-16 14:05 UTC, Sched71 commented on src/core/algorithms/fd/tane/tane.cpp
> +        int dom = index.size();
Maybe not int, but std::size_t or something? We could be in trouble if index size can be bigger than int can hold

2024-10-20 22:35 UTC, Sched71 approved these changes

2024-10-21 22:10 UTC, chernishev approved these changes
Dmitriy Shcheka looked into and approved

2024-10-21 22:42 UTC, merged