New Split optimizations
Desbordante/desbordante-core pull request #506
Opened 2024-12-08 22:36 UTC by MichaelS239

Add new optimizations for Split algorithm

2024-12-13 14:23 UTC, ol-imorozko commented
Since your previous PR #439 has been merged, please rebase this one onto the latest `main`.

2024-12-16 16:04 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
> +    plis_ = std::vector<DistancePositionListIndex>(num_columns_);
```suggestion
    plis_.resize(num_columns_);
```

2024-12-16 16:10 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
> +    plis_ = std::vector<DistancePositionListIndex>(num_columns_);
same thing with `min_max_dif_`

2024-12-16 16:12 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
>      return false;
```suggestion
    return std::ranges::any_of(tuple_pairs_, [this, &d](const auto& pair) { return CheckDF(d, pair); });
```

2024-12-16 16:13 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
>      return false;
maybe other methods could also be simplified in this way by using exact algorithm with readable name instead of a raw loop

2024-12-16 16:16 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
>      if (!search.size()) return {};
```suggestion
    if (search.empty()) return {};
```

2024-12-16 16:17 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
>      }
add `const auto& pair = tuple_pairs_[index];`

2024-12-16 16:18 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
>          dds.splice(dds.end(), remaining_dds);
maybe
```suggestion
        dds.splice(dds.end(), std::move(remaining_dds));
```
?

We don't need `remaining_dds` anymore

2024-12-16 16:19 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
>      dds.splice(dds.end(), merged_dds);
again, I think this should be done:
```suggestion
    dds.splice(dds.end(), std::move(merged_dds));
```

2024-12-30 10:38 UTC, MichaelS239 commented on src/core/algorithms/dd/split/model/distance_position_list_index.cpp
> +}
Should I create a template method like this
```c++
template<typename T>
void DistancePositionListIndex::AddValue(T&& value) {
    auto&& [it, is_value_new] = value_mapping_.try_emplace(std::forward<T>(value), next_cluster_index_);
    ...
}
```
?

2024-12-30 10:50 UTC, MichaelS239 commented on src/core/algorithms/dd/split/model/distance_position_list_index.cpp
> +        AddValue(column.GetDataAsString(index));
Do I need to use `std::move` here? Seems like the returned string from `GetDataAsString` is already an rvalue

2024-12-30 11:08 UTC, MichaelS239 commented on src/core/algorithms/dd/split/split.cpp
> +
As far as I can see, no one is catching these exceptions and the program is intended to crash

2024-12-30 11:15 UTC, MichaelS239 commented on src/core/algorithms/dd/split/split.cpp
> +    double const dif = distances_[column_index][min_cluster][max_cluster - min_cluster];
No, that is
```c++
double const dif = distances_[column_index][std::min(first_cluster, second_cluster)][std::abs(first_cluster - second_cluster)];
```
The first cluster is not always minimal

2024-12-30 11:18 UTC, MichaelS239 commented on src/core/algorithms/dd/split/split.cpp
> +inline bool Split::CheckDF(DF const& dif_func, std::pair<std::size_t, std::size_t> tuple_pair) {
I've measured the performance: without this `inline` the algorithm starts working 2.5 times slower

2025-01-09 10:41 UTC, ol-imorozko commented on src/core/algorithms/dd/split/model/distance_position_list_index.cpp
> +}
yeah

2025-01-09 10:42 UTC, ol-imorozko commented on src/core/algorithms/dd/split/model/distance_position_list_index.cpp
> +        AddValue(column.GetDataAsString(index));
with the current approach with template method, no, you won't need an `std::move` here

2025-01-09 10:51 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
> +    double const dif = distances_[column_index][min_cluster][max_cluster - min_cluster];
oh, yeah, my bad.
then I think
```cpp
    ClusterIndex min_cluster = std::min(first_cluster, second_cluster);
    double const dif = distances_[column_index][min_cluster][std::abs(first_cluster - second_cluster)];
```
Is good. But honestly your approach is good also, so feel free to choose whatever you like more

2025-01-09 11:01 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
> +inline bool Split::CheckDF(DF const& dif_func, std::pair<std::size_t, std::size_t> tuple_pair) {
okay. Maybe we need to use `__attribute__((always_inline))` then, but I'm not sure.

2025-01-09 11:03 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
> +inline bool Split::CheckDF(DF const& dif_func, std::pair<std::size_t, std::size_t> tuple_pair) {
Michael Polyntsov suggested that we should use `[[gnu::always_inline]]` there, and maybe add `[[gnu::hot]]` also

2025-01-09 11:08 UTC, ol-imorozko requested changes

2025-01-09 11:08 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
>  }
```cpp
    return std::ranges::all_of(
        std::views::iota(0, num_columns_),
        [&](model::ColumnIndex column_index) {
            return CheckDFConstraint(dif_func[column_index], column_index, tuple_pair);
        });
```

2025-01-09 11:08 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
>  }
check performance without inline with std::ranges algo btw, maybe this time compiler will inline it

2025-01-12 11:53 UTC, ol-imorozko requested changes

2025-01-12 11:53 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
> +                    }
If you want, you can change it like so:
```suggestion
    pair_bitset.set(df_index, CheckDFConstraint(df_constraint, column_index, {first_index, second_index}));
```
but do as you like

2025-01-12 11:53 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
> +inline bool Split::CheckDF(DF const& dif_func, std::pair<std::size_t, std::size_t> tuple_pair) {
you've added `[[gnu::always_inline]]` to declaration, so `inline` and comment here not needed. You can remove `inline` and move comment to the declaration

2025-01-12 11:53 UTC, ol-imorozko commented on src/core/algorithms/dd/split/split.cpp
> +        return !(CheckDF(lhs, pair) && !CheckDF(rhs, pair));
Maybe
```suggestion
        return !CheckDF(lhs, pair) || CheckDF(rhs, pair);
```

2025-01-12 19:26 UTC, MichaelS239 commented on src/core/algorithms/dd/split/split.cpp
> +inline bool Split::CheckDF(DF const& dif_func, std::pair<std::size_t, std::size_t> tuple_pair) {
Without `inline`, there is a compile error: `error: inlining failed in call to ‘always_inline’ ‘bool algos::dd::Split::CheckDF(const DF&, std::pair<long unsigned int, long unsigned int>)’: function body can be overwritten at link time`

2025-01-13 11:45 UTC, ol-imorozko approved these changes

2025-01-13 13:44 UTC, merged