Add ability to build with Apple Clang
Desbordante/desbordante-core pull request #507
Opened 2024-12-23 16:23 UTC by Petua41

Add ability to build with Apple Clang on macOS.
Add corresponding tests in CI.

2025-01-04 19:04 UTC, Vdaleke requested changes
Thank you for your great work. I'm not completely done with the review yet and there will probably be more comments soon, but I'll post these so you can start fixing them.

I will leave a few comments that cannot be attached to individual files:

1) There are no binding-tests for Clang and macOS Apple Clang. And there may be problems similar to those that caused the https://github.com/Desbordante/desbordante-core/pull/492, I mean DYLD_PATH on macOS. 

2) We keep a short commit history. Pls, squash commits to some parts. I propose squash into 4 like this: CI, src-fixing, CMake, README. 

3) You make great descriptions for all commits, pls copy them in some way to PR description. If someone else looks at the PR, they don't look for commit descriptions, and it's also a good way to present the result.

2025-01-04 19:07 UTC, Vdaleke commented
<img width="860" alt="image" src="https://github.com/user-attachments/assets/ffab228b-54ea-403d-80d8-933f62507547" />

Interesting checks, maybe somewhere in project settings are inlined these names to block merge without them?

2025-01-04 19:12 UTC, Petua41 commented
> Interesting checks, maybe somewhere into project settings these names are inlined to block merge without them?
Yes, it's branch protection rules. I left a comment about it in PR#499

2025-01-04 19:17 UTC, Vdaleke commented
> > Interesting checks, maybe somewhere into project settings these names are inlined to block merge without them?
> 
> Yes, it's branch protection rules. I left a comment about it in PR#499

Oh, I didn't notice there are 2 pull request, is 499 needed at all if this one exists? I suggest closing it and continuing only in this one.

2025-01-04 19:22 UTC, Petua41 commented
> Oh, I didn't notice there are 2 pull request, is 499 needed at all if this one exists? I suggest closing it and continuing only in this one.

There's 3 pull requests. 499 addresses Clang on Linux, 500 -- LLVM Clang on macOS, and this PR addresses Apple Clang.
499 is a part of 500, and 500 is a part of 507. I recommend to review them in this order.
I think, it's better to have 3 different PRs and try to merge as many of them as possible before the release

2025-01-04 19:26 UTC, Petua41 commented on README.md
> +Then you need to install Boost library built with LLVM Clang. Please avoid using Homebrew for this, as the Boost version provided by Homebrew
Homebrew is not designed to use compilers other than Apple Clang, so I don't think it would be reliable solution

2025-01-04 19:31 UTC, Petua41 commented on build.sh
> +    git clone https://github.com/google/googletest/ --branch v1.14.0 --depth 1
This comes from PR#499, but commit with reasons is seems to get lost. There was a bug in googletest, which caused Clang to produce a warning. I'll add this information into PR#499

2025-01-04 19:36 UTC, Petua41 commented on README.md
> +This will make LLVM Clang have greater priority than Apple Clang for your current session.
I didn't found any other working way to build boost with custom compiler. `--toolset` option doesn't work with paths, and for `clang` in selects `/usr/bin/clang`, which is Apple Clang.
We need this trick only for boost installation. For our `build.sh` we use CMake flags.

2025-01-04 19:41 UTC, Vdaleke commented on README.md
> +This will make LLVM Clang have greater priority than Apple Clang for your current session.
> I haven't found any other working way to build boost with custom compiler. 
```
echo "using darwin : : clang++ ;" > user-config.jam
 --user-config=user-config.jam
```
? This is works fine with gcc

2025-01-04 19:53 UTC, Vdaleke commented on README.md
> +Then you need to install Boost library built with LLVM Clang. Please avoid using Homebrew for this, as the Boost version provided by Homebrew
It's true, but there is a good chance that there will be problems with `DYLD_PATH` and homebrew's boost fix it in some way (I couldn't find how, may be you can). 

`export DYLD_LIBRARY_PATH ` is not reliable solution too. There are some problems that such dependency not copied to child processes. https://cibuildwheel.pypa.io/en/stable/faq/#macos-passing-dyld_library_path-to-delocate

I suggest to come back to this later after creating and passing python-binding tests on macOS.

2025-01-04 21:46 UTC, Vdaleke commented
> > Oh, I didn't notice there are 2 pull request, is 499 needed at all if this one exists? I suggest closing it and continuing only in this one.
> 
> There's 3 pull requests. 499 addresses Clang on Linux, 500 -- LLVM Clang on macOS, and this PR addresses Apple Clang. 499 is a part of 500, and 500 is a part of 507. I recommend to review them in this order. I think, it's better to have 3 different PRs and try to merge as many of them as possible before the release

I don't like that they are tightly coupled in CI. It seems to me that when all the fixes are already in place, it's easier to do and review everything together, rather than merge one by one, changing the architecture in the process. And do we really need a release without a pip-package on MacOS?

2025-01-05 00:49 UTC, Vdaleke requested changes
The second part of review.

As for constructors which is in a lot of fixes. I heard about the performance of the aggregates from colleagues at work, and constantly. For example, that's why it is not recommended to use a std::pair, for some reason they added a constructor there and a regular handwritten structure will be faster. But I can't find normal proofs on the Internet.

2025-01-05 00:49 UTC, Vdaleke commented on src/core/algorithms/fd/sfd/cords.cpp
> +    auto start_time = std::chrono::system_clock::now();
What's the reason of it? std::chrono::system_clock::now() is not high_resolution?

2025-01-05 00:49 UTC, Vdaleke commented on src/core/algorithms/md/hymd/column_match_info.h
> +    ColumnMatchInfo(indexes::ColumnMatchSimilarityInfo const& similarity_info,
When you adding a constructor to struct it ceases to be an aggregate. Aggregates have good performance in creating because compiler can just in-place in memory the members. 

I recommend simply replacing the with brace initialization everywhere if possible. Otherwise, the algorithm may lose performance.

This applies to all structures below :(

2025-01-05 00:49 UTC, Vdaleke commented on src/core/util/maybe_unused.h
> +// (see https://stackoverflow.com/questions/50646334/maybe-unused-on-member-variable-gcc-warns-
the link can't be copied to clipboard because it's split into 2 lines

2025-01-05 00:49 UTC, Vdaleke commented on src/tests/test_algo_interfaces.cpp
>  struct KeysTestParams {
The same comments as for HyMD

2025-01-05 00:49 UTC, Vdaleke commented on src/tests/test_pfdtane.cpp
> +    PFDTaneValidationParams(std::vector<PFD>&& fds, algos::PfdErrorMeasure const& error_measure,
May be here it's okay because of previous struct with constructor.

2025-01-05 00:49 UTC, Vdaleke commented on src/tests/test_tane_afd_measures.cpp
> +
The same :(

2025-01-05 00:49 UTC, Vdaleke commented on src/core/util/auto_join_thread.h
> +        return;  // Don't pass exception on
And what's the reason of catching exceptions here?

2025-01-05 00:52 UTC, Vdaleke commented on src/core/util/bitset_extensions.cpp
> +    for (size_t byte_idx{0}; byte_idx < kNumBytes; ++byte_idx) {
I read about why it's better because of cast-checking, but it seems to me copy-initialization is more readable.

2025-01-05 09:17 UTC, Petua41 commented
> As for constructors which is in a lot of comments. I heard about the performance of the aggregates from colleagues at work, and constantly. For example, that's why it is not recommended to use a std::pair, for some reason they added a constructor there and a regular handwritten structure will be faster. But I can't find normal proofs on the Internet.

The only thing I can do is to define constructors conditionnally -- only when aggregate initialization isn't availible.

2025-01-05 09:18 UTC, Petua41 commented on src/core/util/bitset_extensions.cpp
> +    for (size_t byte_idx{0}; byte_idx < kNumBytes; ++byte_idx) {
In this case it's matter of taste, and I saw both variants in other code.

2025-01-05 09:29 UTC, Petua41 commented on src/core/util/bitset_extensions.h
> +        // FIXME(senichenkov): implement custom FindNext for 256-bit (or custom width) bitsets
Yes, in `FDep` class there are 256-bit bitsets. For example, `diff_attr` in method `AddViolatedFDs`.

2025-01-05 09:32 UTC, Petua41 commented on src/core/util/bitset_extensions.cpp
> +    __builtin_unreachable();
It's GCC intrinsic, so there's not so much information about it, but I saw a lot of its usages in other our code.

2025-01-05 09:36 UTC, Petua41 commented on src/core/util/bitset_extensions.h
> +/// If reference to bitset is invalidated, behaviour is undefined!
There's no reference to bitset in `DynamicBitsetIterator`

2025-01-05 09:43 UTC, Petua41 commented on src/core/algorithms/fd/sfd/cords.cpp
> +    auto start_time = std::chrono::system_clock::now();
No, `high_resolution_clock` is `system_clock` only in libstdc++. In libc++ it's `steady_clock`.
See links in the bottom of https://en.cppreference.com/w/cpp/chrono/high_resolution_clock

2025-01-05 09:49 UTC, Petua41 commented on src/core/util/auto_join_thread.h
> +        return;  // Don't pass exception on
Because all constructors are implicitly `noexcept`. I don't think `std::terminate` is a good way of dealing with exceptions in some aysncronous thread. In fact, the only purpose of this class is to avoid `std::terminate` in destructor of `std::thread`.
And I don't think that adding `noexcept(false)` would be better -- no one expects exceptions from destructor.

2025-01-05 13:12 UTC, Vdaleke commented on src/core/util/bitset_extensions.cpp
> +    for (size_t byte_idx{0}; byte_idx < kNumBytes; ++byte_idx) {
Ok, I'll agree, since Google Code Style allows you to choose https://google.github.io/styleguide/cppguide.html#Variable_and_Array_Initialization

2025-01-05 13:20 UTC, Vdaleke commented on src/core/util/bitset_extensions.h
> +/// If reference to bitset is invalidated, behaviour is undefined!
And is this a good solution? So, the iterator is invalidated if changes occur in the dynamic bitset?

2025-01-05 13:29 UTC, Vdaleke commented
> > As for constructors which is in a lot of comments. I heard about the performance of the aggregates from colleagues at work, and constantly. For example, that's why it is not recommended to use a std::pair, for some reason they added a constructor there and a regular handwritten structure will be faster. But I can't find normal proofs on the Internet.
> 
> The only thing I can do is to define constructors conditionnally -- only when aggregate initialization isn't availible.

I don't quite understand why you can't just use brace-initialization everywhere?

2025-01-05 13:33 UTC, Vdaleke commented on src/core/util/bitset_extensions.h
> +        // FIXME(senichenkov): implement custom FindNext for 256-bit (or custom width) bitsets
Then I suggest making the same implementation in FindFirst for the completeness, or make custom for 256-bit in both cases.

2025-01-05 14:04 UTC, Petua41 commented on src/core/util/bitset_extensions.h
> +        // FIXME(senichenkov): implement custom FindNext for 256-bit (or custom width) bitsets
To make custom implementation for 256-bit case won't be so easy, since we don't have 256-bit integers. The only conversion availible for big bitsets is `to_string`.

2025-01-05 14:06 UTC, Petua41 commented
> I don't quite understand why you can't just use brace-initialization everywhere?

Brace-initialization calls constructor. It won't help if we want to get rid of constructors.

2025-01-05 14:31 UTC, Vdaleke commented
> Brace-initialization calls constructor.

It's not true? 

https://learn.microsoft.com/en-us/cpp/cpp/initializing-classes-and-structs-without-constructors-cpp?view=msvc-170#:~:text=When%20a%20class%20or%20struct%20has%20no%20constructor%2C%20you%20provide%20the%20list%20elements%20in%20the%20order%20that%20the%20members%20are%20declared%20in%20the%20class.

2025-01-05 18:33 UTC, p-senichenkov commented on .github/composite-actions/download-libraries/action.yml
>          sudo apt-get install gcc-10 g++-10 cmake build-essential -y
This PR addresses only Clang, and I haven't changed GCC version here. I think, we could bump it's version in some other PR, related to GCC.
Anyway, I don't think we should do it. CI checks compatibility, not effectiveness.

2025-01-05 18:54 UTC, Vdaleke commented on .github/composite-actions/download-libraries/action.yml
>          sudo apt-get install gcc-10 g++-10 cmake build-essential -y
> This PR addresses only Clang, and I haven't changed GCC version here. I think, we could bump it's version in some other PR, related to GCC. 

Yeah, I agree that this is not really relevant to this PR

> Anyway, I don't think we should do it. CI checks compatibility, not effectiveness.

It's good that it checks compatibility with GCC 10, but we also use it to build the pip package. https://github.com/Desbordante/desbordante-core/blob/3fa1249644febe64eb69adc15a2f9959dc819751/.github/workflows/wheel.yml#L74

2025-01-05 19:01 UTC, p-senichenkov commented on CMakeLists.txt
> +            message(WARNING "check will be supressed. Consider using another distro for full ASAN coverage.")
Now these warnings look strange, because they are broken into three separate `message`s:
```
Running on Ubuntu
CMake Warning at CMakeLists.txt:80 (message):
  ASAN is broken in Ubuntu package, therefore alloc-dealloc-mismatch


CMake Warning at CMakeLists.txt:81 (message):
  check will be supressed.  Consider using another distro for full ASAN
  coverage.
```
I'll fix them.
Regarding dot, every CMake line ends with dot, and our messaged don't end with dot. I think, it's better to remove the dot.

2025-01-05 19:12 UTC, p-senichenkov commented on .github/composite-actions/download-libraries/action.yml
>          sudo apt-get install gcc-10 g++-10 cmake build-essential -y
If it's really important, we could use different actions for CI (focused on compatibility) and CD (focused on recency)

2025-01-06 11:14 UTC, p-senichenkov commented on CMakeLists.txt
> +    add_subdirectory("lib/googletest" SYSTEM)
`SYSTEM` subdirectory disables compiler warnings from `googletest`. Other sub-projects that we build ourselves (e. g. 'easylogging`) don't produce warnings, so there's no `SYSTEM`.
I think, there should be `SYSTEM` everywhere, because warnings that come from sub-projects aren't related to Desbordante.

2025-01-06 11:21 UTC, p-senichenkov commented on src/core/util/bitset_extensions.h
> +/// If reference to bitset is invalidated, behaviour is undefined!
Changes can't occur in dynamic bitset -- it's `private`

2025-01-06 11:46 UTC, p-senichenkov commented on build.sh
> +    git clone https://github.com/google/googletest/ --branch v1.14.0 --depth 1
The reasons are in commit 4c9522285c6a5b58009119d1cb90543ee86dbdc1

2025-01-06 11:49 UTC, Vdaleke commented
> In terms of [this page on cppreference](https://github.com/Desbordante/desbordante-core/pull/507), 

Not working link 

> But in most cases we have emplace_back, that cannot be replaced with direct-list-initialization.

Use push_back instead

2025-01-06 11:51 UTC, p-senichenkov commented
> Not working link

https://github.com/Desbordante/desbordante-core/pull/507

2025-01-06 11:51 UTC, p-senichenkov commented
> Not working link

https://en.cppreference.com/w/cpp/language/list_initialization

2025-01-06 11:53 UTC, Vdaleke commented on CMakeLists.txt
> +    add_subdirectory("lib/googletest" SYSTEM)
> I think, there should be `SYSTEM` everywhere, because warnings that come from sub-projects aren't related to Desbordante.

I guess I agree, maybe then add SYSTEM to all dependencies?

2025-01-06 11:57 UTC, Vdaleke commented on src/core/util/bitset_extensions.h
> +/// If reference to bitset is invalidated, behaviour is undefined!
> Changes can't occur in dynamic bitset -- it's `private`

I don't mean the internal field, but the external vector from which it is copied. I think it's also right to maintain a link inside to avoid such a situation and not copy in vain.

2025-01-06 12:06 UTC, p-senichenkov commented on src/core/util/bitset_extensions.h
> +/// If reference to bitset is invalidated, behaviour is undefined!
I don't clearly understand which link do you mean. `DynamicBitsetIterator` iterates through `boost::dynamic_bitset`, which is created in constructor from `std::bitset`.

2025-01-06 12:25 UTC, Vdaleke commented on src/core/util/bitset_extensions.h
> +/// If reference to bitset is invalidated, behaviour is undefined!
I apologize for my inattention. I thought it was an iterator for dynamic_bitset from Boost. Then it is not very clear why we need a separate class for this, if it is just a different implementation of BitsetIterator. I suggest making a specialization of the class with implementation via BitSet in case there is a gcc extension and implementation via dynamic_bitset otherwise.

2025-01-06 12:31 UTC, p-senichenkov commented on src/core/util/bitset_extensions.h
> +/// If reference to bitset is invalidated, behaviour is undefined!
These classes were created when I used SFINAE to check if SGI extensions are availible, and it was hard to make two specializations of one class. Now, with concepts, I think, I can make two specializations.

2025-01-06 14:10 UTC, Vdaleke requested changes

2025-01-06 14:10 UTC, Vdaleke commented on .github/composite-actions/install-dependencies/action.yml
> +  install-toolset:
```
toolset:
    type: choice
    required: true
    options:
      gcc
      lvm-clang
      apple-clang
```

2025-01-06 14:10 UTC, Vdaleke commented on .github/composite-actions/install-dependencies/action.yml
> -    type: boolean
Leave it as is.

2025-01-06 14:10 UTC, Vdaleke commented on .github/composite-actions/install-dependencies/action.yml
> +      if: inputs.install-build-tools == 'apt'
- name: Install build tools
      run: |
        if [[ "${{ inputs.os }}" == "ubuntu" ]]; then
          sudo apt-get update -y
          sudo apt-get install cmake build-essential -y
        elif [[ "${{ inputs.os }}" == "macos" ]]; then
          brew install make cmake
        fi
      shell: bash
      if: inputs.install-build-tools == 'true'

2025-01-06 14:10 UTC, Vdaleke commented on .github/composite-actions/install-dependencies/action.yml
> +    - name: Install GCC toolset
Analogically to build tools installing:
```
- name: Install toolset
  run: |
       ....
  shell: bash
  if: inputs.install-toolset == 'true'

2025-01-06 14:10 UTC, Vdaleke commented on .github/composite-actions/install-dependencies/action.yml
> +    - name: Install Boost built with GCC
Analogically

2025-01-06 14:25 UTC, p-senichenkov commented on .github/composite-actions/install-dependencies/action.yml
> +    - name: Install GCC toolset
We have a lot of toolsets and their choice doesn't depend on OS

2025-01-06 14:45 UTC, Vdaleke commented on .github/composite-actions/install-dependencies/action.yml
> +    - name: Install GCC toolset
> doesn't depend on OS

What do you mean by independent? I suggest to implement 4 possible ways [ubuntu, gcc], [ubuntu, llvm-clang], [macos, llvm-clang], [macos, apple-clang], otherwise the action should be interrupted/failed

2025-01-06 21:20 UTC, Vdaleke commented
Due to ac2ad57.
Let me remind you that at the meeting we agreed to leave in the readme only gcc for Linux and only apple clang for macOS, everything else will move to the wiki.

2025-01-08 23:13 UTC, Vdaleke requested changes
Thanks for the corrections, it looks much better. I left a couple of minor comments and questions. Of the possible major edits, only replacing it with a composition in CI-tests, if it is possible to catch an incorrect configuration.

2025-01-08 23:13 UTC, Vdaleke commented on src/core/util/maybe_unused_on_clang.h
> +#define MAYBE_UNUSED_ON_CLANG [[maybe_unused]]
I don't really like the name attached to the Clang, rename to `MAYBE_UNUSED_FIELD`?

2025-01-08 23:13 UTC, Vdaleke commented on src/tests/test_algo_interfaces.cpp
>  struct KeysTestParams {
Are constructors still here because these are tests and we don't care about performance?

2025-01-09 08:55 UTC, p-senichenkov commented on src/tests/test_algo_interfaces.cpp
>  struct KeysTestParams {
Yes, and in most cases, these `struct`s are created a lot of times and have long names, so direct-list-initialization would be harder to read

2025-01-09 09:07 UTC, p-senichenkov commented on .github/workflows/bindings-tests.yml
> +            runtime-env: DYLD_LIBRARY_PATH=/usr/local/lib:${DYLD_LIBRARY_PATH}
I had this problem on Apple CLang too, but maybe I'm wrong. I'll check it again.

2025-01-09 09:08 UTC, Vdaleke commented on .github/composite-actions/install-dependencies/action.yml
> +        download-command: wget -O boost_1_85_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.85.0/boost_1_85_0.tar.gz/download && tar xzvf boost_1_85_0.tar.gz && mv boost_1_85_0 boost
I don't think there's any point in trying to support old versions of boost, 1.85+ should have been added to all package managers by now. I think it's just worth upgrading the version everywhere.

2025-01-09 09:08 UTC, p-senichenkov commented on .github/workflows/bindings-tests.yml
> +            # Apple Clang is default compiler. No env needed
CMake knows where Homebrew installs `boost`. I had problems only with `ld`

2025-01-09 09:10 UTC, p-senichenkov commented on .github/workflows/check-codestyle.yml
> +          # FIXME(senichenkov): do we need gcc and boost here, or build-tools will be enough?
But the only command I see below is `cmake`...
Does `ZedThree/clang-tidy-review@v0.19.0` call `make`?

2025-01-09 09:12 UTC, Vdaleke commented on .github/workflows/bindings-tests.yml
> +            # Apple Clang is default compiler. No env needed
I rather think about the case, what if someone calls the installation of libraries twice on one runner with different configurations. Then it is worth supporting the last installed configuration and this is the reason why there should be an environment variable setting here too, as it seems to me.

2025-01-09 09:13 UTC, p-senichenkov commented on .github/workflows/core-tests.yml
> +          # Uncomment this to disable macOS-llvm-clang tests:
No, currently `disable`. I remember that we've decided to disable these checks, but I wanted to make sure that they pass before deisabling them.
I'll disable them in the very end, when all other changes to CI will be done

2025-01-09 09:13 UTC, Vdaleke commented on .github/workflows/check-codestyle.yml
> +          # FIXME(senichenkov): do we need gcc and boost here, or build-tools will be enough?
So, cmake does the build, build.sh is just a wrapper around cmake with some flags set.

2025-01-09 09:15 UTC, Vdaleke commented on .github/workflows/core-tests.yml
> +          # Uncomment this to disable macOS-llvm-clang tests:
I'm talking about the comment, you need to uncomment it to enable, not to disable.

2025-01-09 09:18 UTC, p-senichenkov commented on .github/workflows/core-tests.yml
> +        # Maybe separate composite action will be more readable?
Yes, it's possible to implement such logic, for example through `exit 0`.
But, the problem is, that `export ` command must be called in the shell, where `cmake` and `make` will be called.
I think, we can use `env` (https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#env), but I don't have much time to test it.

2025-01-09 09:19 UTC, p-senichenkov commented on .github/workflows/wheel.yml
> +          # FIXME(senichenkov): which os to use here?
Don't we need `wheel`s for macOS?

2025-01-09 09:23 UTC, Vdaleke commented on .github/workflows/wheel.yml
> +          # FIXME(senichenkov): which os to use here?
needed, but this is my task, I will make a pull request on the weekend

2025-01-09 09:24 UTC, p-senichenkov commented on README.md
> +#### macOS dependencies installation (Apple Clang)
"macOS" is a name and they start it with small "m" everywhere (see, for example https://www.apple.com/macos/macos-sequoia/)

2025-01-09 09:25 UTC, Vdaleke commented on .github/workflows/core-tests.yml
> +        # Maybe separate composite action will be more readable?
So you're suggesting leaving it as is because you don't have time to write another version? This solution is generally ok, maybe I'll fix it later using env

2025-01-09 09:26 UTC, p-senichenkov commented on .github/workflows/check-codestyle.yml
> +          # FIXME(senichenkov): do we need gcc and boost here, or build-tools will be enough?
I thought `cmake` only generates Makefile, and then `make` does the compilation

2025-01-09 09:30 UTC, p-senichenkov commented on src/core/util/bitset_extensions.h
> +        0x00'00'00'00'00'00'00'ff, 0x00'00'00'00'00'00'ff'00, 0x00'00'00'00'ff'ff'00'00,
Yes, `clang-format` wants these elements to be placed in one line

2025-01-09 09:32 UTC, Vdaleke commented on README.md
> +#### macOS dependencies installation (Apple Clang)
what about wiki link name https://en.wikipedia.org/wiki/MacOS
but I agree that the name should probably be written with a lowercase letter, for example, I would be very surprised if I saw iPhone with a capital letter

2025-01-09 09:33 UTC, p-senichenkov commented on src/core/util/bitset_extensions.h
> +template <size_t S>
> As far as I understand the concepts, this is not a specialization, but simply another template. Then the templates will be supplied in the order of definition and the second template will never be used, because the conditions include the fulfillment of the conditions of the previous one. The definitions need to be swapped.

I've checked that first specialization is called on `libc++` and second -- on `libstdc++`. As I understand, the most specializaed remplate has the greatest priority

2025-01-09 09:36 UTC, p-senichenkov commented on README.md
> +#### macOS dependencies installation (Apple Clang)
> what about wiki link name https://en.wikipedia.org/wiki/MacOS

I suggest that wiki page was created when macOS called "Mac OS X", which starts with capital M

2025-01-09 09:39 UTC, p-senichenkov commented on src/core/util/maybe_unused_on_clang.h
> +#define MAYBE_UNUSED_ON_CLANG [[maybe_unused]]
I've used this name, because it's what this macro actually does: it checks `__clang__`.
Maybe I'll find a way to check if GCC learned to mark private fields as unused (but it's unlikely)

2025-01-09 09:46 UTC, Vdaleke commented on src/core/util/maybe_unused_on_clang.h
> +#define MAYBE_UNUSED_ON_CLANG [[maybe_unused]]
I understand that this is so, but firstly, suddenly there are other compilers where a similar check would also be needed, for example, maybe msvc, and secondly, from the point of view of a C++ developer, it shouldn’t matter to him that the problem is specifically with the clang, it’s enough for him to just know that we use such a macro for private fields; so, maybe `MAYBE_UNUSED_PRIVATE_FIELD`?

2025-01-09 10:15 UTC, p-senichenkov commented on .github/workflows/bindings-tests.yml
> +            # Apple Clang is default compiler. No env needed
Actually, it's impossible to call this action twice on same runner, because `matrix` is controlled by GitHub

2025-01-09 22:23 UTC, Vdaleke commented on src/core/util/bitset_extensions.h
> +template <size_t S>
This is a very interesting language mechanic that I didn't know about. As for proof of it attach similar example from cppreference

https://en.cppreference.com/w/cpp/language/constraints#Constraint_normalization:~:text=g(0)%3B%20%20%20%20//%20int%20satisfies%20Decrementable%2C%20selects%20%234%20because%20it%20is%20more%20constrained

2025-01-09 22:32 UTC, Vdaleke requested changes
LGTM, just remove `FIXME` pls

2025-01-09 22:32 UTC, Vdaleke commented on src/core/util/bitset_extensions.h
> +        // FIXME(senichenkov): implement custom FindFirst for 256-bit (or custom width) bitsets
Replace FIXME with TODO

2025-01-09 22:32 UTC, Vdaleke commented on src/core/util/bitset_extensions.h
> +        // FIXME(senichenkov): implement custom FindNext for 256-bit (or custom width) bitsets
the same

2025-01-10 10:49 UTC, Vdaleke approved these changes

2025-01-10 11:57 UTC, Vdaleke commented on .github/workflows/core-tests.yml
>          cfg:
I suggest to move `cfg` after `os` and `compiler` to have actions sorted by os, compiler, config in actions table inside PR.

2025-01-11 17:13 UTC, BUYT-1 commented on src/core/algorithms/md/hymd/md_lhs.h
> -        return values_.emplace_back(offset).ccv_id;
What happened here?

2025-01-11 17:15 UTC, polyntsov commented on src/core/util/auto_join_thread.h
> +class AutoJoinThread {
In c++20 we have `std::jthread`

2025-01-11 18:17 UTC, Vdaleke requested changes
Sorry for the request after approval, but it seems like an easy way to get rid of the double name in actions.

2025-01-11 18:17 UTC, Vdaleke commented on .github/workflows/bindings-tests.yml
> +          - os: { long-name: ubuntu-latest, short-name: ubuntu }
Close 2nd point of https://github.com/Desbordante/desbordante-core/issues/512.
Use only full name

2025-01-11 18:17 UTC, Vdaleke commented on .github/workflows/core-tests.yml
> +    runs-on: ${{ matrix.os.image }}
The same.

2025-01-11 18:17 UTC, Vdaleke commented on .github/workflows/core-tests.yml
> +          - {name: ubuntu, image: ubuntu-latest}
The same.

2025-01-11 18:22 UTC, p-senichenkov commented on .github/workflows/bindings-tests.yml
> +          - os: { long-name: ubuntu-latest, short-name: ubuntu }
I wanted to create a global map, because it's easier to read than ternary oeprator. Also, it would be hard to adapt ternary operator to add, for example `windows`, or some custom runner.

2025-01-11 18:26 UTC, Vdaleke commented on .github/workflows/bindings-tests.yml
> +          - os: { long-name: macos-14, short-name: macos }
What's the point of using macos-14? Maybe change to macos-latest?

2025-01-11 18:28 UTC, Vdaleke commented on src/python_bindings/od/bind_od.cpp
> +                        res.push_back(ListOD{lhs, rhs});
Can we use implicit conversation here instead of explicit? I mean not to use ListOD and rely on type-deduction

2025-01-11 18:28 UTC, Vdaleke commented on src/core/algorithms/od/order/order_utility.cpp
> +        indexed_byte_data.push_back(IndexedByteData{k, byte_data[k]});
The same here and in other places

2025-01-11 18:30 UTC, p-senichenkov commented on src/python_bindings/od/bind_od.cpp
> +                        res.push_back(ListOD{lhs, rhs});
No, because it would be aggregate-initialization (see https://en.cppreference.com/w/cpp/language/list_initialization), which isn't supported.

2025-01-11 18:32 UTC, p-senichenkov commented on .github/workflows/bindings-tests.yml
> +          - os: { long-name: macos-14, short-name: macos }
The reason was that I've only testsed it on `macOS-14`, but now it shouldn't be a problem.
Actually, after this change we could use `matrix.os = ubuntu/macos` and `runs-os: ${{ matrix.os }}-latest`.

2025-01-11 18:51 UTC, p-senichenkov commented on src/python_bindings/od/bind_od.cpp
> +                        res.push_back(ListOD{lhs, rhs});
![изображение](https://github.com/user-attachments/assets/df68e5a7-9e81-487d-9319-25e8dcb202a6)
Actually, it works. Sorry for desinformation.

2025-01-11 19:06 UTC, Vdaleke commented on .github/workflows/bindings-tests.yml
> +          - os: { long-name: ubuntu-latest, short-name: ubuntu }
In install-dependencies make such changes:
```
  os:
    type: string
    required: true

    - name: Get short OS name
      run: |
        function get_short_os_name() {
          if [[ $1 == *"macos"* ]]; then
            echo "macos"
          elif [[ $1 == *"ubuntu"* ]]; then
            echo "ubuntu"
          else
            echo "unknown"
          fi
        }
        
        echo "OS=$(get_short_os_name ${{ inputs.os }})" >> $GITHUB_ENV
      shell: bash
```
then use `env.OS` where you need.  ?

2025-01-11 19:07 UTC, Vdaleke commented on .github/workflows/bindings-tests.yml
> +          - os: { long-name: macos-14, short-name: macos }
I suggest to change to macos-latest and use function inside install-dependencies which I suggested

2025-01-11 19:14 UTC, p-senichenkov commented on .github/workflows/bindings-tests.yml
> +          - os: { long-name: ubuntu-latest, short-name: ubuntu }
The only problem is that we'll need to duplicate this function, in `core-tests` and in `binding-tests`. So, I suggest making it a separate `composite-action`.
Also, as for me, to determine runner image based on its short name would be more readable and convenient if we decide to add some other workflows.

2025-01-11 19:29 UTC, Vdaleke commented on .github/workflows/bindings-tests.yml
> +          - os: { long-name: ubuntu-latest, short-name: ubuntu }
> The only problem is that we'll need to duplicate this function

No, just put it inside install-dependencies

> Also, as for me, to determine runner image based on its short name would be more readable and convenient if we decide to add some other workflows.

As for me, it is good to see the version on which it is launched, besides, with a short name it will not be possible to launch several versions of one operating system

2025-01-11 22:12 UTC, Vdaleke commented on .github/composite-actions/install-dependencies/action.yml
> +          if [[ $1 == *"macos"* ]]; then
Maybe swap macos and ubuntu? so that there is the same order everywhere.

2025-01-12 09:32 UTC, Vdaleke commented
I managed to build a pip package for macOS under llvm-clang and now I think that llvm-clan should be the default compiler for macOS because llvm-clang has more extensions and it should be better in performance?
Then I suggest leaving such configurations:
```
{macos-latest, llvm-clang, Release},
{macos-latest, llvm-clang, Debug},
{macos-latest, llvm-clang,  Debug, UB},
{macos-latest, llvm-clang,  Debug, Address},
{macos-latest, apple-clang, Release},
```
The last one to check compatibility with apple clang in terms of extensions and standard support.

And then I think that in the readme we need to insert the assembly configuration under the llvm clang, since we choose it as the main one.

2025-01-12 09:41 UTC, p-senichenkov commented
> I managed to build a pip package for macOS under llvm-clang and now I think that llvm-clan should be the default compiler for macOS because llvm-clang has more extensions and it should be better in performance?

Why do you think LLVM Clang will be more effective? The only difference is aggregate initialization, which is corrected anyway. I think, "native" compiler *can* be better (and *can* be worse -- we should test it).

However, Apple Clang building instruction are much shorter, as there's no need in compiling `boost`. Since Apple Clang is pre-installed on macOS, users can build project without much preparation, like with GCC on Linux. I don't think we should place LLVM Clang in README as "main" compiler.

2025-01-12 12:08 UTC, Vdaleke commented
> The only difference is aggregate initialization, which is corrected anyway.

No that's not the only difference, llvm clang provides bitset and jthread extensions for which we have provided a replacement that should not be as efficient as the implementation from the clang compiler

> However, Apple Clang building instruction are much shorter, as there's no need in compiling boost. Since Apple Clang is pre-installed on macOS, users can build project without much preparation, like with GCC on Linux. I don't think we should place LLVM Clang in README as "main" compiler.

Maybe it's true, but I think it's worth making some kind of annotation that we use llvm-clang as the default compiler for building the pip package and it's worth trying to build using it

2025-01-12 12:17 UTC, p-senichenkov commented
> No that's not the only difference, llvm clang provides bitset and jthread extensions for which we have provided a replacement that should not be as efficient as the implementation from the clang compiler

`libc++`, which is used in **any** Clang does **not** provide bitset extensions and `thread`. See https://en.cppreference.com/w/cpp/compiler_support

2025-01-12 13:29 UTC, Vdaleke commented
> `libc++`, which is used in **any** Clang does **not** provide bitset extensions and `thread`.

I don't quite understand, it was necessary to add jthread and the bitset extension only when apple-clang was added. Can't we use libstdc++?

2025-01-12 13:34 UTC, p-senichenkov commented
> it was necessary to add jthread and the bitset extension only when apple-clang was added

No, it was necessary even on Linux (see https://github.com/Desbordante/desbordante-core/pull/499)

> Can't we use libstdc++?

We can, but there's no point in compiling with Clang, if we link it with GCC's standard library. In that case we could just close this PR without merging.

2025-01-12 13:36 UTC, Vdaleke commented
> > it was necessary to add jthread and the bitset extension only when apple-clang was added
> 
> No, it was necessary even on Linux (see #499)
> 
> > Can't we use libstdc++?
> 
> We can, but there's no point in compiling with Clang, if we link it with GCC's standard library. In that case we could just close this PR without merging.

now I think that we should supply a pip package built for gcc even on macos, but that's not your concern anymore, maybe I'll add it myself

2025-01-12 14:50 UTC, Vdaleke approved these changes

2025-01-30 10:31 UTC, p-senichenkov commented
> Could you describe in more detail what error is happening and why, because I didn't quite understand what they were writing in the issue without context. The solution seems ok, but I would leave a comment on why we added CC export here, unlike other places.

The problem is, CMake somehow cannot locate `clang-scan-deps` tool when C compiler is set to GCC. I don't quite understand which update caused this error, but I'm sure it's not modern Ubuntu problem (see Ubuntu version in https://github.com/Desbordante/desbordante-core/actions/runs/13030263166/job/36347763368). As far as I understand from discussion of mentioned issue, this tool is needed to scan dependencies of C++ modules.

2025-01-30 10:41 UTC, Vdaleke commented
Check this answer https://stackoverflow.com/a/77801270/16427597. CMake has variable to set path to `clang-scan-deps` and such a solution is at least more obvious than the fact that the C compiler helps him find it.

2025-01-30 10:47 UTC, p-senichenkov commented
> Check this answer https://stackoverflow.com/a/77801270/16427597. CMake has variable to set path to `clang-scan-deps` and such a solution is at least more obvious than the fact that the C compiler helps him find it.

This way I need to hard-code `clang-scan-deps` path. In that answer, they've first created symlink to the tool in `/usr/local/bin`, because it's location isn't in `PATH` by default. This solution will work only on one exact system.

2025-01-30 10:49 UTC, Vdaleke commented
> This way I need to hard-code `clang-scan-deps` path. In that answer, they've first created symlink to the tool in `/usr/local/bin`, because it's location isn't in `PATH` by default. This solution will work only on one exact system.

OK, then i think a comment will be enough

2025-02-01 09:54 UTC, merged